version: '2'
services: 

  nginx:
    build:
      context: .
    environment: 
      - TARGET_HOSTS='mongodb:27017'
    ports:
      - 3000:3000

  mognodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=bacon123
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
